name: Deploy Bot

on:
  push:
    branches:
      - main  # Push hone par trigger hoga
  schedule:
    - cron: '0 */3 * * *'  # Har 3 ghante mein run hoga

jobs:
  deploy:
    runs-on: ubuntu-latest  # Latest Ubuntu version pe run karega

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # GitHub repository ko checkout karega

      - name: Set up Python
        uses: actions/setup-python@v4  # Python ko setup karega
        with:
          python-version: '3.9'  # Python version define karein

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install telebot flask pymongo aiohttp python-telegram-bot  # Install dependencies

      - name: Make scripts executable
        run: |
          chmod +x *  # All files ko executable banayein

      - name: Start the bot
        run: |
          echo "Starting the bot..."
          nohup python3 nand.py &  # Bot ko background mein start karein
          tail -f nohup.out  # Log dekhte rahe

      - name: Keep bot running and restart if it crashes
        run: |
          echo "Running bot in a loop..."
          while true; do
            python3 nand.py || echo "Bot crashed. Restarting in 5 seconds...";
            sleep 5;
          done
